---
title: "Seminar Programmiersysteme - T52: testthat"
author: "Adrian Stämpfli, Matr.Nr. 9529020"
header-includes: \usepackage[ngerman]{babel} \usepackage{graphicx} \usepackage{float} \pagenumbering{roman} 
output:
  pdf_document:
    fig_caption: yes
    highlight: tango
    number_sections: yes
    toc: yes
date: "`r format(Sys.time(), '%B %d, %Y')`"
documentclass: report
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
bibliography: bibliography.bib
preamble: |
  % Any extra latex you need in the preamble
abstract: |
  Die Schweizer Sanitätsnotrufzentralen bearbeiten jährlich mehr als 580‘000 medizinische Notrufe, aus welchen ca. 450’000 Einsätze für die Rettungsdienste entstehen. Die effiziente Disposition und Bearbeitung dieser Einsätze ist eine grosse Herausforderung. `sim911` simuliert die Hilfsfristerreichung und erlaubt es verschiedene Massnahmen wie Stützpunktverschiebungen, temporäre Stützpunkte oder Veränderungen der Dienstpläne zu bewerten. Hierzu nutzt `sim911` historische Einsatzdaten, eine Dispositionsstrategie sowie Stützpunkte und Dienstpläne als Eingaben und berechnet daraus verschiedene für das Rettungswesen relevante Kennzahlen und grafische Auswertungen. `sim911` wurde im Rahmen eines KTI geförderten Projektes (KTI 15782.1 PFES-ES) entwickelt und bereits in mehreren Praxisprojekten erfolgreich angewandt. `sim911` wird durch das Institut für Modellbildung und Simulation aktiv weiterentwickelt.
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.pos = 'H')
```

\newpage
\pagenumbering{arabic} 

# Einführung in R 
Was ist R. [siehe @Peng2014, Abschnitt 2]

\newpage

# Testing in R  
## 

## Testing Approaches  

## Testing Frameworks

### testit

### testthat

### RUnit und svUnit

# Testthat (und Devtools)  
[@Wickham2015]

\newpage

# Konklusionen für die Arbeit am IMS


Struktur Der Vortrag sollte klar strukturiert sein. Bei wissenschaftlichen Arbeiten bietet sich meist folgende Grobgliederung an:
1. Überblick über den Vortrag
2. Kurze Einführung in das Themengebiet
3. Klares Herausarbeiten der Problemstellung oder der wesentlichen Ideen des zu behan- delnden Themas
4. Entwicklung der Lösung zu diesem Problem oder Darstellung der wesentlichen Ideen
5. Zusammenfassung des Vorgetragenen und Bewertung der Ergebnisse
6. Quellenangaben

\newpage

\listoffigures

# Literatur





